### ISSUE TITLE
crypto.discoveryKey API docs say "publicKey" but source has "tree" as argument

### ISSUE THREAD

**Issue by decentral1se** [mafintosh/hypercore-crypto#3]
* https://github.com/mafintosh/hypercore-crypto#hash--cryptodiscoverykeypublickey
* https://github.com/mafintosh/hypercore-crypto/blob/09b09cfc80f6e0aa51e1dee1bab6e948ca5c6a60/index.js#L84

**Comment by mafintosh** [comment]
Typo, should be public key here

**Comment by mafintosh** [comment]
Fixed in master
